"""add: post title translation

Revision ID: 0f215efc3855
Revises: 9d453307e6c4
Create Date: 2026-02-27 20:12:39.870714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f215efc3855"
down_revision: Union[str, Sequence[str], None] = "9d453307e6c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("title_en", sa.String(length=255), nullable=True))
    op.add_column("post", sa.Column("body_uz", sa.Text(), nullable=True))
    op.add_column("post", sa.Column("body_ru", sa.Text(), nullable=True))
    op.add_column("post", sa.Column("body_en", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "body_en")
    op.drop_column("post", "body_ru")
    op.drop_column("post", "body_uz")
    op.drop_column("post", "title_en")
    # ### end Alembic commands ###
