"""add: post title translation

Revision ID: 9d453307e6c4
Revises: 6a13f353e693
Create Date: 2026-02-27 19:42:39.981434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d453307e6c4"
down_revision: Union[str, Sequence[str], None] = "6a13f353e693"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("title_uz", sa.String(length=255), nullable=True))
    op.add_column("post", sa.Column("title_ru", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "title_ru")
    op.drop_column("post", "title_uz")
    # ### end Alembic commands ###
