"""add: deleted email

Revision ID: ed692e5ecb91
Revises: bdb1a2463720
Create Date: 2026-02-06 20:15:49.277608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed692e5ecb91"
down_revision: Union[str, Sequence[str], None] = "bdb1a2463720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("deleted_email", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_email")
    # ### end Alembic commands ###
